<a href="https://colab.research.google.com/github/25CristopherJoshuaReyesGtz1405/MachineLearning/blob/main/Machine_Learning_Y_Deep_Learning_Pr%C3%A1ctica_No_1_Unidad_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![TecNM](https://drive.google.com/uc?id=1HP9R3V9XnozjtY08gGdKhoCKo76MKgLr)

---
<div align="center">

  ## **Machine Learning y Deep Learning**

  ### **Unidad 1 - Introduccion a Machine Learning y Deep Learning**

  #### Practica No. 1 - Data Wrangling

  ##### **Docente** - **Dr. José Gabriel Rodríguez Rivas**
  ##### **Estudiante** - **Cristopher Joshua Reyes Gutiérrez**

</div>

---

### **Introducción**
En el ciclo de vida de cualquier proyecto de Ciencia de Datos y *Machine Learning*, la etapa de preparación de los datos (conocida técnicamente como **Data Wrangling**) constituye, a menudo, más del 80% del tiempo dedicado al desarrollo. Los conjuntos de datos provenientes del mundo real raramente se presentan en un formato ideal; suelen contener valores ausentes, errores de formato, ruido y tipos de datos inconsistentes que impiden el correcto funcionamiento de los algoritmos matemáticos.

La calidad de un modelo predictivo depende intrínsecamente de la calidad de los datos con los que se entrena (*"Garbage In, Garbage Out"*). Por consiguiente, es imperativo aplicar procesos rigurosos de limpieza, imputación y transformación para convertir datos crudos en información fiable y estructurada. En el presente documento, se aborda el tratamiento del conjunto de datos "Automóviles", el cual presenta diversos retos de limpieza que deben ser resueltos antes de cualquier análisis exploratorio o modelado predictivo.

### **Objetivo General De La Práctica**
Implementar técnicas fundamentales de *Data Wrangling* utilizando la librería Pandas en Python, con el fin de transformar un conjunto de datos crudo y con inconsistencias en una estructura limpia, estandarizada y apta para el entrenamiento de modelos de Inteligencia Artificial.

### **Objetivos Específicos De La Práctica**
1.  **Identificar y estandarizar valores nulos:** Detectar caracteres no estándar (como "?") que representan ausencia de información y convertirlos al formato lógico adecuado (`NaN`).
2.  **Gestionar datos faltantes:** Aplicar estrategias de imputación estadística (media para variables numéricas y moda para variables categóricas) para preservar la mayor cantidad de información posible sin introducir sesgos significativos.
3.  **Corregir tipos de datos:** Validar y transformar las variables a sus tipos numéricos correspondientes (`int`, `float`) para permitir operaciones matemáticas y análisis estadísticos.
4.  **Asegurar la integridad del dataset:** Eliminar registros que carezcan de información en la variable objetivo (*target*), garantizando así la viabilidad del aprendizaje supervisado.


---

## **1. Configuración del Entorno de Trabajo**
En esta fase inicial se procede a la importación de las bibliotecas fundamentales para el análisis de datos. Se utiliza **Pandas** para la manipulación de los datos, **NumPy** para operaciones numéricas, y las librerías **Matplotlib** y **Seaborn** para la generación de gráficos que faciliten la comprensión de la distribución de los datos.

In [78]:
import pandas as pd
import matplotlib as plt
from matplotlib import pyplot
import numpy as np

## **2. Carga de Datos**
Se realiza la carga del conjunto de datos "**Automóviles**" desde una fuente remota. Los datos crudos son almacenados en un estructura de tipo ***DataFrame*** de Pandas, lo cual permite su manipulación programática. Adicionalmente, se verifica la correcta lectura del archivo mediante una visualización preliminar de las primeras filas y la dimensión total de la matriz de datos.

In [79]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [80]:
file_url = "1DnNb3pn7BunaPkxaIKs7tZbScXxFqxgA"
url = f"https://drive.google.com/uc?id={file_url}"
df = pd.read_csv(url)

## **3. Análisis Exploratorio y Detección de Anomalías**
Antes de proceder con la limpieza, se ejecuta un diagnóstico del estado actual del dataset. Se ha detectado que los valores faltantes en este conjunto de datos no están representados por el estándar `NaN` (Not a Number), sino por el carácter de texto "?".

Por consiguiente, se lleva a cabo la estandarización de estos valores, reemplazando todos los signos de interrogación por valores nulos reales reconocibles por el sistema. Posteriormente, se genera un mapa de calor (*heatmap*) para visualizar gráficamente la distribución y densidad de los datos faltantes en cada variable.

In [81]:
# Muestra la información general de la tabla, más concretamente los tipos de datos de cada una de las columnas
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   symboling          205 non-null    int64
 1   normalized-losses  205 non-null    object
 2   make               205 non-null    object
 3   fuel-type          205 non-null    object
 4   aspiration         205 non-null    object
 5   num-of-doors       205 non-null    object
 6   body-style         205 non-null    object
 7   drive-wheels       205 non-null    object
 8   engine-location    205 non-null    object
 9   wheel-base         205 non-null    float64
 10  length             205 non-null    float64
 11  width              205 non-null    float64
 12  height             205 non-null    float64
 13  curb-weight        205 non-null    int64
 14  engine-type        205 non-null    object
 15  num-of-cylinders   205 non-null    object
 16  engine-size        205 non-null    int64
 17  fuel-system        205 non-null    object
 18  bore               205 non-null    object
 19  stroke             205 non-null    object
 20  compression-ratio  205 non-null    float64
 21  horsepower         205 non-null    object
 22  peak-rpm           205 non-null    object
 23  city-mpg           205 non-null    int64
 24  highway-mpg        205 non-null    int64
 25  price              205 non-null    object
dtypes: float64(5), int64(5), object(16)
memory usage: 41.8+ KB

In [82]:
# Mostrar las primeras 10 filas
# Observar que en la columna normalized-losses hay valores con ?, debiendo ser enteros
df.head(10)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.4,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.4,8.0,115,5500,18,22,17450
5,2,?,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.4,8.5,110,5500,19,25,15250
6,1,158,audi,gas,std,four,sedan,fwd,front,105.8,...,136,mpfi,3.19,3.4,8.5,110,5500,19,25,17710
7,1,?,audi,gas,std,four,wagon,fwd,front,105.8,...,136,mpfi,3.19,3.4,8.5,110,5500,19,25,18920
8,1,158,audi,gas,turbo,four,sedan,fwd,front,105.8,...,131,mpfi,3.13,3.4,8.3,140,5500,17,20,23875
9,0,?,audi,gas,turbo,two,hatchback,4wd,front,99.5,...,131,mpfi,3.13,3.4,7.0,160,5500,16,22,?

In [83]:
# Gracias a la implementación de la función "replace", se reemplaza el valor de ?, (Valor no estandarizado), por NaN, que permite una mejor organización de la información
df.replace("?", np.nan, inplace = True)
df.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.4,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.4,8.0,115,5500,18,22,17450

In [84]:
valores_faltantes = df.isnull()
valores_faltantes.head(10)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True

## **4. Estrategias de Imputación y Tratamiento de Valores Faltantes**

Una vez estandarizados los valores nulos, se procede a la fase crítica de imputación. El objetivo de esta etapa es rectificar la ausencia de información en las 7 columnas afectadas, aplicando métodos estadísticos que minimicen la alteración de la varianza original y la introducción de sesgos en el conjunto de datos.

### **4.1. Imputación por Media Aritmética (Variables Continuas)**
Para las variables numéricas que presentan una distribución continua, se opta por sustituir los valores faltantes (`NaN`) con el promedio (*mean*) de la columna. Esta técnica es seleccionada para preservar la tendencia central de los datos. El procedimiento se aplica a las siguientes características:

* **normalized-losses:** Se calcula el promedio de las pérdidas normalizadas y se utiliza para rellenar las 41 entradas faltantes, manteniendo la consistencia en la evaluación de riesgos del vehículo.
* **bore (Diámetro del cilindro):** Se computa la media de los valores existentes para completar los 4 registros vacíos, asegurando la integridad de las especificaciones del motor.
* **stroke (Carrera del pistón):** De manera similar, se imputa el promedio a los valores ausentes para no perder información sobre la geometría del motor.
* **horsepower (Caballos de fuerza):** Siendo una variable crucial para el rendimiento, se utiliza la media aritmética para suavizar las ausencias y permitir comparaciones de potencia equitativas.
* **peak-rpm (Revoluciones pico):** Se estandarizan los valores faltantes mediante el promedio global de revoluciones por minuto.

#### Pero Antes.... Habrá Contar Los Valores Faltantes de las Columnas

- Podemos usar un ciclo **for** en Pyhton para verificar la cantidad de valores faltantes en cada columna.
- Como se mencionó arriba, "True" representa un valor faltante y "False" un valor presente en el conjunto de datos.
- En el cuerpo del ciclo for el método ".value_counts()" cuenta el número de valores tipo "True".

>>> Ejecutando imputación por Media...
    Variable 'normalized-losses': Nulos reemplazados con 122.0000
    Variable 'bore': Nulos reemplazados con 3.3307
    Variable 'stroke': Nulos reemplazados con 3.2569
    Variable 'horsepower': Nulos reemplazados con 103.4030
    Variable 'peak-rpm': Nulos reemplazados con 5117.6654
>>> Variable 'num-of-doors': Nulos reemplazados con 'four'
>>> Registros eliminados por ausencia de precio: 0

✅ Tipología de datos corregida exitosamente.

In [86]:
df.isna().sum().sort_values()

symboling             0
make                  0
fuel-type             0
aspiration            0
drive-wheels          0
body-style            0
wheel-base            0
engine-location       0
height                0
curb-weight           0
length                0
width                 0
engine-type           0
num-of-cylinders      0
fuel-system           0
engine-size           0
highway-mpg           0
compression-ratio     0
city-mpg              0
num-of-doors          2
peak-rpm              2
horsepower            2
bore                  4
stroke                4
price                 4
normalized-losses    41
dtype: int64

In [87]:
valores_faltantes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   symboling          205 non-null    bool
 1   normalized-losses  205 non-null    bool
 2   make               205 non-null    bool
 3   fuel-type          205 non-null    bool
 4   aspiration         205 non-null    bool
 5   num-of-doors       205 non-null    bool
 6   body-style         205 non-null    bool
 7   drive-wheels       205 non-null    bool
 8   engine-location    205 non-null    bool
 9   wheel-base         205 non-null    bool
 10  length             205 non-null    bool
 11  width              205 non-null    bool
 12  height             205 non-null    bool
 13  curb-weight        205 non-null    bool
 14  engine-type        205 non-null    bool
 15  num-of-cylinders   205 non-null    bool
 16  engine-size        205 non-null    bool
 17  fuel-system        205 non-null    bool
 18  bore               205 non-null    bool
 19  stroke             205 non-null    bool
 20  compression-ratio  205 non-null    bool
 21  horsepower         205 non-null    bool
 22  peak-rpm           205 non-null    bool
 23  city-mpg           205 non-null    bool
 24  highway-mpg        205 non-null    bool
 25  price              205 non-null    bool
dtypes: bool(26)
memory usage: 5.3 KB

In [88]:
avg_norm_loss = df["normalized-losses"].astype("float").mean(axis=0)
print("Average of normalized-losses:", avg_norm_loss)

Average of normalized-losses: 122.0

In [89]:
df["normalized-losses"].replace(np.nan, avg_norm_loss, inplace=True)

/tmp/ipython-input-2599940699.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["normalized-losses"].replace(np.nan, avg_norm_loss, inplace=True)

In [90]:
df.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,122.0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,122.0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,122.0,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.4,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.4,8.0,115,5500,18,22,17450

In [91]:
avg_bore=df['bore'].astype('float').mean(axis=0)
print("Average of bore:", avg_bore)

Average of bore: 3.3297512437810943

In [92]:
df['bore'].replace(np.nan, avg_bore, inplace=True)

/tmp/ipython-input-1549772624.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['bore'].replace(np.nan, avg_bore, inplace=True)

In [93]:
df.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,122.0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,122.0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,122.0,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.4,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.4,8.0,115,5500,18,22,17450

In [94]:
avg_stroke=df['stroke'].astype('float').mean(axis=0)
print("Average of stroke:", avg_stroke)

Average of stroke: 3.255422885572139

In [95]:
df["stroke"].replace(np.nan, avg_stroke, inplace=True)

/tmp/ipython-input-3589830416.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["stroke"].replace(np.nan, avg_stroke, inplace=True)

In [96]:
avg_horsepower = df['horsepower'].astype('float').mean(axis=0)
print("Average horsepower:", avg_horsepower)

Average horsepower: 104.25615763546799

In [97]:
df["horsepower"].replace(np.nan, avg_horsepower, inplace=True)

/tmp/ipython-input-1074039262.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["horsepower"].replace(np.nan, avg_horsepower, inplace=True)

In [98]:
aveg_peakrpm = df['peak-rpm'].astype('float').mean(axis=0)
print("Average peak rpm:", aveg_peakrpm)

Average peak rpm: 5125.369458128079

In [99]:
df["peak-rpm"].replace(np.nan, aveg_peakrpm, inplace=True)

/tmp/ipython-input-1035361207.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["peak-rpm"].replace(np.nan, aveg_peakrpm, inplace=True)

Remplazar valores faltantes con la Frecuencia (moda)
Num Doors

In [100]:
# Mediante el uso de la función value_counts(), nos permite contabilizar los valores que se tiene dentro de una columna y de esa manera nos permite conocer la moda...
df["num-of-doors"].value_counts()

num-of-doors
four    114
two      89
Name: count, dtype: int64

In [101]:
# Una vez obtenido la media aritmética, podemos reemplazar, dentro de los valores nulos, los valores que nos arrojo la moda...
df["num-of-doors"].replace(np.nan, "four", inplace=True);

/tmp/ipython-input-4253441308.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["num-of-doors"].replace(np.nan, "four", inplace=True);

In [102]:
df["num-of-doors"].value_counts()

num-of-doors
four    116
two      89
Name: count, dtype: int64

### Eliminar valores faltantes

Para el caso de los valores faltantes en la columna Price, **se decide borrar todo el renglón**. Esto se debe a que no es recomendable sustituir el valor porque esta columna es la que se usara para predecir el precio de un vehiculo con similares caracteristicas.

In [103]:
df.dropna(subset=["price"], axis=0, inplace=True)

In [104]:
df.reset_index(drop=True, inplace=True)

In [105]:
df.head(20)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,122.0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,122.0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,122.0,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.4,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.4,8.0,115,5500,18,22,17450
5,2,122.0,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.4,8.5,110,5500,19,25,15250
6,1,158,audi,gas,std,four,sedan,fwd,front,105.8,...,136,mpfi,3.19,3.4,8.5,110,5500,19,25,17710
7,1,122.0,audi,gas,std,four,wagon,fwd,front,105.8,...,136,mpfi,3.19,3.4,8.5,110,5500,19,25,18920
8,1,158,audi,gas,turbo,four,sedan,fwd,front,105.8,...,131,mpfi,3.13,3.4,8.3,140,5500,17,20,23875
9,2,192,bmw,gas,std,two,sedan,rwd,front,101.2,...,108,mpfi,3.5,2.8,8.8,101,5800,23,29,16430
10,0,192,bmw,gas,std,four,sedan,rwd,front,101.2,...,108,mpfi,3.5,2.8,8.8,101,5800,23,29,16925
11,0,188,bmw,gas,std,two,sedan,rwd,front,101.2,...,164,mpfi,3.31,3.19,9.0,121,4250,21,28,20970
12,0,188,bmw,gas,std,four,sedan,rwd,front,101.2,...,164,mpfi,3.31,3.19,9.0,121,4250,21,28,21105
13,1,122.0,bmw,gas,std,four,sedan,rwd,front,103.5,...,164,mpfi,3.31,3.19,9.0,121,4250,20,25,24565
14,0,122.0,bmw,gas,std,four,sedan,rwd,front,103.5,...,209,mpfi,3.62,3.39,8.0,182,5400,16,22,30760
15,0,122.0,bmw,gas,std,two,sedan,rwd,front,103.5,...,209,mpfi,3.62,3.39,8.0,182,5400,16,22,41315
16,0,122.0,bmw,gas,std,four,sedan,rwd,front,110.0,...,209,mpfi,3.62,3.39,8.0,182,5400,15,20,36880
17,2,121,chevrolet,gas,std,two,hatchback,fwd,front,88.4,...,61,2bbl,2.91,3.03,9.5,48,5100,47,53,5151
18,1,98,chevrolet,gas,std,two,hatchback,fwd,front,94.5,...,90,2bbl,3.03,3.11,9.6,70,5400,38,43,6295
19,0,81,chevrolet,gas,std,four,sedan,fwd,front,94.5,...,90,2bbl,3.03,3.11,9.6,70,5400,38,43,6575

##   **5. Corregir el formato de los datos**

- El último paso para limpiar los datos es revisar y asegurar que su formato sea el correcto (int, float, text u otro.)
- Con Pandas sería

   - **dataframe.dtype()** para revisar el tipo de dato

   - **datafframe.astype()** para cambiar el tipo de dato

Vamos a listar los tipos de datos para cada columna

In [106]:
df.dtypes

symboling              int64
normalized-losses     object
make                  object
fuel-type             object
aspiration            object
num-of-doors          object
body-style            object
drive-wheels          object
engine-location       object
wheel-base           float64
length               float64
width                float64
height               float64
curb-weight            int64
engine-type           object
num-of-cylinders      object
engine-size            int64
fuel-system           object
bore                  object
stroke                object
compression-ratio    float64
horsepower            object
peak-rpm              object
city-mpg               int64
highway-mpg            int64
price                 object
dtype: object

#### Como resultado del paso anterior vemos que:

- Algunas columnas no tienen el tipo correcto de dato.
- Las variables numericas deben ser de tipo 'float' o 'int',
- las variables de cadenas (categoria) deben ser de tipo 'object'.
- Las variables **'bore' y 'stroke'** son valores numericos que describen los motores, asi que podemos esperar que sean del tipo 'float' o 'int'; sin embargo, se muestran como tipo 'objetc'.  

Debemos convertir los tipos de datos al formato apropiado para cada columna utilizando el método **"astype()"**.

In [107]:
df[["bore", "stroke"]] = df[["bore", "stroke"]].astype("float")
df[["normalized-losses"]] = df[["normalized-losses"]].astype("int")
df[["price"]] = df[["price"]].astype("float")
df[["peak-rpm"]] = df[["peak-rpm"]].astype("float")

In [108]:
df.dtypes

symboling              int64
normalized-losses      int64
make                  object
fuel-type             object
aspiration            object
num-of-doors          object
body-style            object
drive-wheels          object
engine-location       object
wheel-base           float64
length               float64
width                float64
height               float64
curb-weight            int64
engine-type           object
num-of-cylinders      object
engine-size            int64
fuel-system           object
bore                 float64
stroke               float64
compression-ratio    float64
horsepower            object
peak-rpm             float64
city-mpg               int64
highway-mpg            int64
price                float64
dtype: object

##   **6. Estandarización de los datos**

Como parte del proceso de limpieza y transformacion de los datos, debemos tomar en cuenta que los datos normalmente se recolectan de diferentes agencias y pueden tener formatos distintos.

**¿Qué es la estandarización?**

La estandarización es el proceso de transformar datos en un formato común que permita al investigador realizar comparaciones significativas.

**Ejemplo Práctico**

En está práctica, se utliza los datos de consumo de gasolina en unidades de medida de millas por galon:

- city-mpg

- highway-mpg

Podemos inferir, que en nuestro país, es más común referirnos al consumo de combustible en litros por cada 100  Km.

</p>
<p>¿Será necesario <b>transformar los datos</b> para convertir Milas Por Galón (MPG) en Litros por cada 100 km, para que esto pueda ser un proceso de estandarización completo?</p>

**La formula de conversión es**  

L/100km = 235 / m.p.g.

In [109]:
# Para la Conversión de las Unidades, se creará otra nueva columna para ahí almacenar el resultado de la conversión
df['city-L/100km'] = 235 / df["city-mpg"]

In [110]:
# revisar los datos transformados
# Ver al final que se agrego la nueva columna

df.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,city-L/100km
0,3,122,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,mpfi,3.47,2.68,9.0,111,5000.0,21,27,13495.0,11.190476
1,3,122,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,mpfi,3.47,2.68,9.0,111,5000.0,21,27,16500.0,11.190476
2,1,122,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,mpfi,2.68,3.47,9.0,154,5000.0,19,26,16500.0,12.368421
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,mpfi,3.19,3.40,10.0,102,5500.0,24,30,13950.0,9.791667
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,mpfi,3.19,3.40,8.0,115,5500.0,18,22,17450.0,13.055556

In [111]:
# Enseguida vamos a transformar los datos de la columna highway-mpg
# Millas por galon en carretera
# Aqui lo hacemos directamente sobre la columna

df["highway-mpg"] = 235 / df["highway-mpg"]

# renombramos la columna "highway-mpg" a "highway-L/100km"
df.rename(columns={"highway-mpg":"highway-L/100km"}, inplace=True)

# checar los datos transformado
df.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-L/100km,price,city-L/100km
0,3,122,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,mpfi,3.47,2.68,9.0,111,5000.0,21,8.703704,13495.0,11.190476
1,3,122,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,mpfi,3.47,2.68,9.0,111,5000.0,21,8.703704,16500.0,11.190476
2,1,122,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,mpfi,2.68,3.47,9.0,154,5000.0,19,9.038462,16500.0,12.368421
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,mpfi,3.19,3.40,10.0,102,5500.0,24,7.833333,13950.0,9.791667
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,mpfi,3.19,3.40,8.0,115,5500.0,18,10.681818,17450.0,13.055556

## **7. Normalizacion de los Datos**

La normalización es el proceso de transformar los valores de algunas variables dentro de un rango similar.
La normalización típica incluye el redimensionado de las variables para que los valores del rango sean entre 0 y 1.
Dado que el rango de valores de los datos sin procesar varía ampliamente, en algunos algoritmos de aprendizaje automático, las funciones objetivas no funcionarán correctamente sin normalización.
Si una de las características tiene una amplia gama de valores, la distancia se regirá por esta característica en particular. Por lo tanto, el rango de todas las características debe normalizarse para que cada característica contribuya aproximadamente de manera proporcional.
Existen difernetes métodos para la normalizacion de datos

El escalado de características es un método que se utiliza para normalizar el rango de variables independientes o características de los datos. En el procesamiento de datos, también se conoce como normalización de datos y generalmente se realiza durante el paso de procesamiento previo de datos.

En este práctica se realizará lo siguiente:

Remplazar el valor original por: (valor original) / (valor máximo)

In [112]:
# Visualizamos las columnas a normalizar

df[["length","width","height"]].head()

   length  width  height
0   168.8   64.1    48.8
1   168.8   64.1    48.8
2   171.2   65.5    52.4
3   176.6   66.2    54.3
4   176.6   66.4    54.3

In [113]:
# intercambiamos el  valor original por el (valor original) / (valor máximo)

df['length'] = df['length'] / df['length'].max()
df['width']  = df['width'] / df['width'].max()
df['height'] = df['height']/df['height'].max()

In [114]:
# Volvemos a verificar

df[["length","width","height"]].head()

     length     width    height
0  0.811148  0.890278  0.816054
1  0.811148  0.890278  0.816054
2  0.822681  0.909722  0.876254
3  0.848630  0.919444  0.908027
4  0.848630  0.922222  0.908027

### **8. Variables dummy o indicadoras**
En ocasiones, un conjunto de datos contiene variables categóricas (o cualitativas) con dos o más categorias. Por ejemplo, género, estado civil, o en este caso, el tipo de combustible a usar (gas o diesel)

Una variable dummy (tonta) es una variable numérica usada para etiquetar categorías.
Son llamadas "tonta" porque los números en ellas no tienen ningun significado.
¿Para que se usa una variable indicadora?

Algunos algoritmos de aprendizaje automático, como por ejemplo la regresión no entiende palabras, solo números, por lo tanto, es necesario convertir las variables categoricas a valores numéricos.
Las variables dummy o indicadoras sirven para identificar categorias o clase a las que pertenecen las observaciones.
Existen diversos métodos para generar variables indicadoras

Usaremos el método Pandas 'get_dummies' para asignarle valores numéricos a diferentes categorias de tipo de combustible.
Metodo LabelEncoder de la librería scikitlearn (es una biblioteca para aprendizaje automático de software libre para el lenguaje de programación Python)

In [115]:
# Primero, se verifica los tipos de combustible que existen...
df['fuel-type'].value_counts()

fuel-type
gas       181
diesel     20
Name: count, dtype: int64

#####**-> Método LabelEncoder Con La Librería "Sklearn"**

In [116]:
# Se importa la librería LabelEncoder
from sklearn.preprocessing import LabelEncoder
LabEncoder = LabelEncoder()

In [117]:
# Se agrega una nueva columna donde codificaremos el tipo de gasolina a variable numérica
df['fuel-type_code'] = LabEncoder.fit_transform(df['fuel-type'])
df.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-L/100km,price,city-L/100km,fuel-type_code
0,3,122,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,3.47,2.68,9.0,111,5000.0,21,8.703704,13495.0,11.190476,1
1,3,122,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,3.47,2.68,9.0,111,5000.0,21,8.703704,16500.0,11.190476,1
2,1,122,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,2.68,3.47,9.0,154,5000.0,19,9.038462,16500.0,12.368421,1
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,3.19,3.40,10.0,102,5500.0,24,7.833333,13950.0,9.791667,1
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,3.19,3.40,8.0,115,5500.0,18,10.681818,17450.0,13.055556,1

In [118]:
# Verificamos la columna que acabamos de agregar
df['fuel-type_code'].value_counts()

fuel-type_code
1    181
0     20
Name: count, dtype: int64

### Método get_dummies de Pandas

- Convierta la variable categórica en variables ficticias/indicadoras.